export type PropertyFieldWidth = "full" | "half" | "third" | "twoThird"

type PropertyWidthMap = Partial<Record<string, PropertyFieldWidth>>

const createWidthMap = (
  full: string[] = [],
  half: string[] = [],
  third: string[] = [],
  twoThird: string[] = [],
): PropertyWidthMap => ({
  ...Object.fromEntries(full.map((field) => [field, "full"])),
  ...Object.fromEntries(half.map((field) => [field, "half"])),
  ...Object.fromEntries(third.map((field) => [field, "third"])),
  ...Object.fromEntries(twoThird.map((field) => [field, "twoThird"])),
})

const propertyLayouts: Record<string, PropertyWidthMap> = {
  apartment: createWidthMap(
    [
      "property_title",
      "postal_code",
      "full_address",
      "map_location",
      "amenities",
      "additional_description",
    ],
    [
      "deal_type",
      "ownership_document_status",
      "parking_count",
      "elevator_count",
    ],
    [
      "area_sqm",
      "bedrooms_count",
      "construction_year",
      "floor_number",
      "building_floors_count",
      "units_per_floor",
      "has_parking",
      "has_storage",
      "has_elevator",
    ],
  ),
  villa_house: createWidthMap(
    [
      "property_title",
      "utilities",
      "recreational_amenities",
      "postal_code",
      "full_address",
      "map_location",
      "additional_description",
    ],
    ["has_parking", "parking_capacity"],
    [
      "deal_type",
      "property_type",
      "property_usage",
      "land_area_sqm",
      "building_area_sqm",
      "construction_year",
      "bedrooms_count",
      "building_floors_count",
      "ownership_document_status",
    ],
  ),
  land_garden: createWidthMap(
    [
      "property_title",
      "utilities",
      "existing_structures_description",
      "full_address",
      "map_location",
      "additional_description",
    ],
    [],
    [
      "asset_type",
      "ownership_document_status",
      "plot_division_status",
      "land_area_sqm",
      "road_access_type",
      "has_wall",
    ],
  ),
  commercial_office_property: createWidthMap(
    [
      "property_title",
      "has_business_permit",
      "amenities",
      "full_address",
      "map_location",
      "additional_description",
    ],
    [],
    [
      "property_type",
      "deal_type",
      "ownership_document_status",
      "area_sqm",
      "frontage_width_m",
      "building_position",
      "has_parking",
      "parking_count",
      "has_elevator",
    ],
  ),
  passenger_car: createWidthMap(
    ["vehicle_title", "body_condition", "additional_description"],
    [
      "brand",
      "model_name",
      "has_third_party_insurance",
      "third_party_insurance_expiry_date",
    ],
    [
      "production_year",
      "body_color",
      "mileage_km",
      "fuel_type",
      "transmission_type",
      "technical_condition",
      "plate_number",
      "chassis_number",
      "engine_number",
    ],
  ),
  motorcycle_scooter: createWidthMap(
    ["vehicle_title", "additional_description"],
    ["has_insurance", "insurance_expiry_date"],
    [
      "vehicle_type",
      "brand",
      "model_name",
      "production_year",
      "engine_capacity_or_power",
      "mileage_km",
      "fuel_type",
      "body_color",
      "technical_condition",
      "plate_number",
      "chassis_number",
      "engine_number",
    ],
  ),
  heavy_vehicle_bus: createWidthMap(
    ["vehicle_title", "additional_description"],
    [
      "usage_type",
      "capacity_description",
      "technical_condition",
      "body_chassis_condition",
      "has_technical_inspection",
      "technical_inspection_expiry_date",
      "has_insurance",
      "insurance_expiry_date",
    ],
    [
      "vehicle_type",
      "brand",
      "model_name",
      "production_year",
      "mileage_km",
      "fuel_type",
      "plate_number",
      "chassis_number",
      "engine_number",
    ],
  ),
  pickup_van: createWidthMap(
    ["vehicle_title", "capacity_description", "additional_description"],
    [
      "technical_condition",
      "body_condition",
      "has_insurance",
      "insurance_expiry_date",
    ],
    [
      "vehicle_type",
      "brand",
      "model_name",
      "production_year",
      "body_color",
      "mileage_km",
      "fuel_type",
      "transmission_type",
      "usage_type",
      "plate_number",
      "chassis_number",
      "engine_number",
    ],
  ),
  clothing: createWidthMap(
    ["goods_title", "additional_description"],
    [],
    [
      "goods_type",
      "brand",
      "product_code",
      "goods_condition",
      "size",
      "color",
      "material",
      "quantity",
      "origin_country",
      "has_defect",
    ],
    ["defect_description"],
  ),
  digital_electronics: createWidthMap(
    ["goods_title", "key_specifications", "included_accessories"],
    ["quantity", "registry_status", "has_warranty", "warranty_expiry_date"],
    [
      "goods_type",
      "brand",
      "model_name",
      "serial_or_imei",
      "goods_condition",
      "color",
      "has_defect",
    ],
    ["defect_description"],
  ),
  home_appliances: createWidthMap(
    ["goods_title", "included_accessories", "additional_description"],
    ["has_warranty", "warranty_expiry_date"],
    [
      "goods_type",
      "brand",
      "model_name",
      "serial_number",
      "goods_condition",
      "purchase_or_production_year",
      "color",
      "dimensions",
      "quantity",
      "has_defect",
    ],
    ["defect_description"],
  ),
  wholesale_goods: createWidthMap(
    ["goods_title", "delivery_terms", "additional_description"],
    [
      "quality_grade",
      "packaging_type",
      "has_warranty",
      "warranty_expiry_date",
    ],
    [
      "goods_type",
      "brand",
      "goods_condition",
      "quantity",
      "unit_type",
      "origin_country",
      "batch_number",
      "production_date",
      "expiry_date",
      "has_defect",
    ],
    ["defect_description"],
  ),
}

export function getTransactionPropertyWidth(
  subCategorySlug: string | undefined,
  propertyName: string,
): PropertyFieldWidth {
  if (!subCategorySlug) return "full"
  return propertyLayouts[subCategorySlug]?.[propertyName] || "full"
}
